### PR TITLE
BIP126: Grammar fix and review

### PR DESCRIPTION
**Pull request by dcousens**
ping @justusranvier,  I only just saw https://github.com/OpenBitcoinPrivacyProject/bips/pull/3,  so I've partially started review here.  I can move the comments there if needed.

### CODE REVIEW

**Comment by dcousens** [comment]
> When a Bitcoin transaction contains inputs that reference previous transaction outputs sent to different Bitcoin addresses

Does this BIP also apply to non-addressable output scripts?

>  defining standard forms for transactions containing heterogenous input scripts.

It seems so,  might be worth making that consistent?

**Comment by dcousens** [comment]
> The formation of a standard form HIT is not possible in the following cases:

Wouldn't it also be unavoidable if the number of inputs required can't afford to be split into the number of outputs required (aka, to meet rules `The number of unique output scripts must be equal to the number of unique inputs scripts` and `
At least one pair of outputs must be of equal value.`) without compromising the amount they actually need send?

**Comment by dcousens** [comment]
> Find the smallest combination of inputs whose value is at least the value of the desired spend.

Is this the _total_ desired spend?  If so,  what is the value of the "desired" spend in step 2?
If not (as it appears to be indicated in step 3), how is this value chosen?

**Comment by dcousens** [comment]
> Clients which create intentional HITs must have the capability to form alternate form HITs, and must do so for a non-zero fraction of the transactions they create.

By this do you mean a change in the procedure? Or do you mean the method by which the inputs are chosen must be non-deterministic for some portion of transactions created?
Or?

**Comment by dcousens** [comment]
@kristovatlas I hope you don't mind me reviewing this here,  it seemed the most coherent place.  But I'd be happy to take this to email or a GitHub issue if you'd prefer.

**Comment by justusranvier** [comment]
@dcousens 

> Does this BIP also apply to non-addressable output scripts?
> It seems so, might be worth making that consistent?

I don't understand what you mean by either of these questions. Can you give a specific example of what you're talking about?

> Is this the total desired spend? If so, what is the value of the "desired" spend in step 2?
> If not (as it appears to be indicated in step 3), how is this value chosen?

Yes, this does need to be clarified.

If there is only one party forming the transaction, then then "spend output" and "change output" in step 3 are actually additional change outputs. In this step, "spend output" really means an output of a specified value. It's explained more precisely in the Rules section.

If more than party is forming the transaction, then each party gets one output of the designated size, and (probably) one change output.

> By this do you mean a change in the procedure? Or do you mean the method by which the inputs are chosen must be non-deterministic for some portion of transactions created?
> Or?

Mostly the procedure is written from the perspective of a normal wallet which is encountering unavoidable HITs as part of its normal operation. Those wallets will sometimes be capable of forming standard form transactions, and sometimes need to create alternate form transactions, and sometimes won't be able to follow this procedure at all.

Clients that allow multiple parties to form HITs will usually be able to create any form they want, and only rarely be constrained.

If intentional HITs always use standard form, then that means it's possible to find alternate form HITs on the blockchain and assume they are probably unintentional. To prevent this, clients that form intentional HITs should sometimes choose to make alternate form transactions even if they could have created a standard form transaction.

**Comment by kristovatlas** [comment]
ACK f51a8e1d0eb4870069cccde1f739964aeca93515

**Comment by kristovatlas** [comment]
ACK 05e96d2500258724f4d2cb04b1d803aea045c6bf

**Comment by kristovatlas** [comment]
@dcousens thanks for the review. are you still doing additional review, or is this ready to be merged?

**Comment by kristovatlas** [comment]
Also, this is a perfectly good place to post your feedback, I think -- thanks

**Comment by kristovatlas** [comment]
I've ACK'd these commits, please submit a new PR for additional changes.

**Comment by dcousens** [comment]
Thanks @kristovatlas,  sorry I've been hammered at work this week.
If I find any other changes I'll make a new PR.

**Pull request merged**
